### PR TITLE
Fix EditCommand tests

### LINKED ISSUE #220: Fix EditCommandTest

### PR DESCRIPTION
**Pull request by jereeemyyyy**
# Things Done

* Fix all related issues regarding the edit command tests.
* Temp fix to JsonSerializableClientHubTest
  * Make it such that everytime getTypicalClientHub is called, a fresh copy of the data is created to ensure that all tests are working a "fresh" client hub.

# Need to do

* Need to relook at our implementation for `edit` method.

close #220

### CODE REVIEW

File: src/test/java/seedu/address/testutil/PersonBuilder.java [hunk 1]
```diff
@@ -62,6 +72,21 @@ public PersonBuilder(Person personToCopy) {
...
+        Phone phone = new Phone(DEFAULT_PHONE);
+        Email email = new Email(DEFAULT_EMAIL);
+        Address address = new Address(DEFAULT_ADDRESS);
+        Set<ClientType> clientTypes = new HashSet<>(SampleDataUtil.getClientTypeSet(DEFAULT_CLIENT_TYPE));
+        Description description = new Description(DEFAULT_DESCRIPTION);
+        Set<Reminder> reminders = DEFAULT_REMINDER_SET;
+
+        return new Person(name, phone, email, address, clientTypes, description, reminders);
+    }
+
```
Comment (rubinnn) [inline src/test/java/seedu/address/testutil/PersonBuilder.java:89]: Good abstraction of default person

**Review by rubinnn — COMMENTED** [review]
LGTM
