### PR TITLE
Fix the add reminder command

### LINKED ISSUE #212: Fix add reminder

### PR DESCRIPTION
**Pull request by jereeemyyyy**
# Things done

* When new reminder is add, the fullname will be shown instead of the input name.

close #212

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java [hunk 1]
```diff
@@ -70,7 +70,10 @@ public CommandResult execute(Model model) throws CommandException {
         // Check if there is exactly one match
         if (matchingPersons.size() == 1) {
             Person person = matchingPersons.get(0);
-            person.addReminder(toAdd);
+
+            // Creates a new reminder with the full name of the person
+            Reminder reminderWithFullName = toAdd.getReminderWithFullName(person.getName().fullName);
```
Comment (L-rrrr) [inline src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java:75]: Nice changes to display the full name of the person!

Comment (L-rrrr) [inline src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java:75]: Clear naming!

File: src/main/java/seedu/address/model/reminder/Reminder.java [hunk 2]
```diff
@@ -90,4 +90,8 @@ public String toString() {
                 .add("description", description)
                 .toString();
     }
+
+    public Reminder getReminderWithFullName(String fullName) {
```
Comment (L-rrrr) [inline src/main/java/seedu/address/model/reminder/Reminder.java:94]: Good changes!
