### PR TITLE
Fix the main Find Command for client types

### LINKED ISSUE #184: BUG: Find Command for the client type prefix
# Issues

If we assume we got 2 users (with their client types) in ClientHub:
1. Rubin -> `Investment`, `Healthcare`
2. Harith -> `Investment`

* When the user types `find c/Investment Healthcare` it should return Rubin since he have client types `Investment` and `Healthcare` which aligns with the behaviour of the shortcut version of find client type: `fc`. However, the current `find c/` returns nothing.

### PR DESCRIPTION
**Pull request by jereeemyyyy**
# Things done

* Add a string split to split the string into separate tokens in the form of a String array. 
For eg. Investment Plan will be split into ["Investment", "Plan"].

close #184

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -74,27 +74,32 @@ public Command parse(String args) throws ParseException {
...
         } else if (trimmedArgs.startsWith(PREFIX_CLIENT_TYPE)) {
             String clientTypeKeywords = trimmedArgs.substring(PREFIX_CLIENT_TYPE.length()).trim();
             if (clientTypeKeywords.isEmpty() || !clientTypeKeywords.matches("^[a-zA-Z0-9\\s]+$")) {
                 throw new ParseException(
                         String.format(MESSAGE_INVALID_COMMAND_FORMAT, FindClientTypeCommand.MESSAGE_USAGE));
             }
-            return new FindClientTypeCommand(new ClientTypeContainsKeywordsPredicate(List.of(clientTypeKeywords)));
+            String[] clientTypeKeywordsArr = clientTypeKeywords.split("\\s+");
+
+            return new FindClientTypeCommand(new ClientTypeContainsKeywordsPredicate(List.of(clientTypeKeywordsArr)));
```
Comment (rubinnn) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java:102]: Good changes!

**Review by rubinnn — COMMENTED** [review]
LGTM!
