### PR TITLE
Update Code to fix bug

### LINKED ISSUE #195: [BUG] `delete` command
# Issues
* No big issues with the functionality of the command

Screenshot 2024-10-31 at 4 36 11 PM

* Need to refine the formatting for the output message of invalid command inputs

Screenshot 2024-10-31 at 4 38 41 PM

* Currently, `delete 23` is not considered a **invalid** command. (ClientHub is treating `23` as a name)
  * Since, our add command has a constraint that `name` should only contain letters, space and parenthesis, the constraint should be the same to make the fields  more consistent.

# Suggestions
Screenshot 2024-10-31 at 4 31 38 PM

* Can maybe add more meaningful message when there is a wrong usage of the command
  * For eg. `The client cannot be found in ClientHub! n\ Use the list command to see all your clients!`

# User Guide related
Screenshot 2024-10-31 at 4 23 32 PM

* For this, maybe can add 1 more line saying that `delete David Lim` without `/` at the end would also work since the specified name is **exact**.

### PR DESCRIPTION
**Pull request by rubinnn**
# Thing done
- Updated formatting of error messages
- Added more info like "use list command to check clients"
- Changed parser logic to no longer allow for non-Name inputs

close #195

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java [hunk 1]
```diff
@@ -20,6 +21,12 @@ public class DeleteCommandParser implements Parser<DeleteCommand> {
      */
     public DeleteCommand parse(String args) throws ParseException {
         String personNames = args.trim();
+        try {
+            Name name = ParserUtil.parseName(personNames);
+        } catch (ParseException pe) {
+            throw new ParseException(
+                    String.format(MESSAGE_INVALID_COMMAND_FORMAT, DeleteCommand.MESSAGE_USAGE));
+        }
```
Comment (jereeemyyyy) [inline src/main/java/seedu/address/logic/parser/DeleteCommandParser.java:29]: Why not just do

```
if (!Name.isValidName(personNames)) {
  throw new ParseException(....);
}


```

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java [hunk 2]
```diff
@@ -21,11 +21,9 @@ public class DeleteCommandParser implements Parser<DeleteCommand> {
...
     public DeleteCommand parse(String args) throws ParseException {
         String personNames = args.trim();
-        try {
-            Name name = ParserUtil.parseName(personNames);
-        } catch (ParseException pe) {
-            throw new ParseException(
-                    String.format(MESSAGE_INVALID_COMMAND_FORMAT, DeleteCommand.MESSAGE_USAGE));
+        if (!Name.isValidName(personNames)) {
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+                    DeleteCommand.MESSAGE_USAGE));
```
Comment (jereeemyyyy) [inline src/main/java/seedu/address/logic/parser/DeleteCommandParser.java:26]: Nice changes!

**Review by jereeemyyyy — COMMENTED** [review]
LGTM!
