### PR TITLE
Fix the name displayed

### LINKED ISSUE #243: [BUG] `add` command
# Issue
- Adding a person will only take the first written name
  - Adding "bOb" will save the name as "bOb"
  - Adding "Bob" aftewards will result in an overlap

### PR DESCRIPTION
**Pull request by ahmadsyuaib**
# Things done

- Changed the add command such that all names saved is in the format of first letter capital and the rest small
  - i.e. bOb --> Bob, aLIcE --> Alice
- Changed persons to clients

Closes #243

### CODE REVIEW

**Comment by L-rrrr** [comment]
Good!

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -40,9 +40,9 @@ public class AddCommand extends Command {
             + PREFIX_CLIENT_TYPE + "Plan B "
             + PREFIX_DESCRIPTION + "Likes to eat a lot ";
 
-    public static final String MESSAGE_SUCCESS = "New person added: %1$s";
-    public static final String MESSAGE_DUPLICATE_PERSON = "This name already exists in the address book. If the "
-            + "newly added person has the same name, Please add use () to add more information after the name "
+    public static final String MESSAGE_SUCCESS = "New client added: %1$s";
```
Comment (L-rrrr) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:43]: Good changes!

File: src/main/java/seedu/address/logic/commands/FindAddressCommand.java [hunk 2]
```diff
@@ -15,7 +15,7 @@ public class FindAddressCommand extends Command {
 
     public static final String COMMAND_WORD = "fa";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all persons whose address contain any of "
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all clients whose address contain any of "
```
Comment (L-rrrr) [inline src/main/java/seedu/address/logic/commands/FindAddressCommand.java:18]: Good that you spot all the persons and change it to clients!

File: src/main/java/seedu/address/model/person/Name.java [hunk 3]
```diff
@@ -28,7 +28,18 @@ public class Name {
     public Name(String name) {
         requireNonNull(name);
         checkArgument(isValidName(name), MESSAGE_CONSTRAINTS);
-        fullName = name;
+
+        String[] words = name.split(" ");
```
Comment (L-rrrr) [inline src/main/java/seedu/address/model/person/Name.java:32]: Good to make the format of the names standardized!

**Comment by L-rrrr** [comment]
Good!
