### PR TITLE
Branch bug fixes

### LINKED ISSUE #193: [BUG] `help` Command
# Issues
* Need to finish adding all the commands of ClientHub into the summary list in the help window.

# Suggestions
* Can organise it better and increase readability
* Group related commands together
  * For eg. Group all the find commands under the heading **Find**

### PR DESCRIPTION
**Pull request by Harithhh06**
# Things done

* Updated help window with added short commands and new commands for reminder
* Standardised a client type in SampleDataUtil
* Checkstyle and typos

close #193

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -59,8 +59,6 @@ public AddCommand(Person person) {
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
 
-
-
```
Comment (ahmadsyuaib) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:63]: Good catch!

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -233,11 +233,6 @@ public Optional<Description> getDescription() {
             return Optional.ofNullable(description);
         }
 
-        // Edit Command doesn't allow editing of reminders
-        //        public void setReminders(Set<Reminder> reminders) {
-        //            this.reminders = (reminders != null) ? new HashSet<>(reminders) : null;
-        //        }
-
```
Comment (ahmadsyuaib) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:240]: Removing dead code!

File: src/main/java/seedu/address/ui/HelpWindow.java [hunk 3]
```diff
@@ -18,27 +18,37 @@ public class HelpWindow extends UiPart<Stage> {
     public static final String USERGUIDE_URL = "https://ay2425s1-cs2103t-f10-1.github.io/tp/UserGuide.html";
     public static final String USERGUIDE_REF = "For more info, refer to the user guide: \n" + USERGUIDE_URL;
     public static final String ADD_HELP_HEADER = "Add contacts: ";
-    public static final String ADD_HELP = "add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS d/DESCRIPTION [c/CLIENT_TYPE]";
+    public static final String ADD_HELP_1 = "add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS d/DESCRIPTION [c/CLIENT_TYPE]";
+    public static final String ADD_HELP_2 = "a n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS d/DESCRIPTION [c/CLIENT_TYPE]";
+
```
Comment (ahmadsyuaib) [inline src/main/java/seedu/address/ui/HelpWindow.java:23]: Good changes!

**Review by ahmadsyuaib — APPROVED** [review]
LGTM! Keep it up Harith!
