### PR TITLE
Refine ViewCommand 

### LINKED ISSUE #118: Add more test cases for ViewCommand

### LINKED ISSUE #161: Refine ViewCommand
* Use CommandExceptions to handle invalid inputs
* Improve readability 
* Add Java Docs

### PR DESCRIPTION
**Pull request by jereeemyyyy**
# Things done

* Add new testcases for View Command
* Use CommandExceptions to handle invalid inputs
* Improve readability

close #161, close #118

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 1]
```diff
@@ -23,6 +24,12 @@ public class ViewCommand extends Command {
             + "Parameters: NAME\n"
             + "Example: " + COMMAND_WORD + " " + "alice";
 
+    public static final String MORE_THAN_ONE_PERSON_VIEW_MESSAGE =
+            "\nMultiple clients found. Please specify the name of your client further.";
+
+    public static final String NO_PERSON_FOUND_VIEW_MESSAGE =
+            "\nClient not found. Use the list command to see all clients";
+
```
Comment (rubinnn) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java:32]: Good abstraction of View messages

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 2]
```diff
@@ -32,27 +39,27 @@ public ViewCommand(NameContainsKeywordsPredicate predicate) {
...
 
         // Check if there is anyone in the filtered list
         if (model.getDisplayPersons().isEmpty()) {
-            return new CommandResult(
+            throw new CommandException(
                     String.format(Messages.MESSAGE_PERSON_LISTED_OVERVIEW_FOR_VIEW,
-                            model.getDisplayPersons().size())
-                            + "\nPlease specify the name further to view."
+                    model.getDisplayPersonsListSize())
+                    + NO_PERSON_FOUND_VIEW_MESSAGE
```
Comment (rubinnn) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java:53]: Good check to throw exception

File: src/main/java/seedu/address/logic/commands/ViewCommand.java [hunk 3]
```diff
@@ -32,27 +39,27 @@ public ViewCommand(NameContainsKeywordsPredicate predicate) {
...
         // Check if there are duplicates
         if (model.getDisplayPersons().size() > 1) {
-            return new CommandResult(
-                    String.format(Messages.MESSAGE_PERSONS_LISTED_OVERVIEW,
-                            model.getDisplayPersons().size())
-                            + "\nDuplicates found. Please specify the name further."
+            throw new CommandException(
+                    String.format(Messages.MESSAGE_PERSON_LISTED_OVERVIEW_FOR_VIEW,
+                    model.getDisplayPersonsListSize())
+                    + MORE_THAN_ONE_PERSON_VIEW_MESSAGE
```
Comment (rubinnn) [inline src/main/java/seedu/address/logic/commands/ViewCommand.java:62]: Good use of exception

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 4]
```diff
@@ -146,11 +146,11 @@ public static void showPersonAtIndex(Model model, Index targetIndex) {
      * Asserts that the given {@code command} successfully deletes the person with the given {@code name} in the
      * {@code actualModel}, and the filtered list in the {@code actualModel} is updated to show all persons.
      */
-    public static void assertCommandFailureWithNewList(DeleteCommand command, String name,
+    public static void assertCommandFailureWithNewList(Command command, String userInput,
                                                   Model actualModel, String expectedMessage) {
         List<Person> expectedFilteredList = new ArrayList<>(actualModel.getDisplayPersons())
                 .stream().filter(p -> p.getName().fullName
-                .toLowerCase().contains(name.toLowerCase())).toList();
+                .toLowerCase().contains(userInput.toLowerCase())).toList();
```
Comment (rubinnn) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java:153]: Good changes to accomadate other commands

File: src/test/java/seedu/address/logic/commands/ViewCommandTest.java [hunk 5]
```diff
@@ -56,31 +54,76 @@ public void equals() {
...
+        assertCommandFailureWithNewList(command, "K", model, String.format(
+                MESSAGE_PERSON_LISTED_OVERVIEW_FOR_VIEW + ViewCommand.MORE_THAN_ONE_PERSON_VIEW_MESSAGE, 2));
+    }
+
+    @Test
+    public void execute_mixedCaseFullName_success() {
+        CommandResult expectedCommandResult = new CommandResult(
+                String.format(MESSAGE_PERSON_LISTED_OVERVIEW_FOR_VIEW, 1), false, true, false);
+        NameContainsKeywordsPredicate predicate = preparePredicate("bEnSoN mEiEr");
+        ViewCommand command = new ViewCommand(predicate);
```
Comment (rubinnn) [inline src/test/java/seedu/address/logic/commands/ViewCommandTest.java:120]: Good new TestCases
